Repository HyperPlay-Gaming/hyperplay-ui, pull requests merged in 2024-07, with the labels that each got.

#336 [chore]: Remove unused website components
  package.json
  src/components/Banner/Banner.module.scss
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/index.tsx
  src/components/NavigationBarV2/NavigationBarV2.module.scss
  src/components/NavigationBarV2/NavigationBarV2.stories.tsx
  src/components/NavigationBarV2/components/MobileMenu/MobileMenu.module.scss
  src/components/NavigationBarV2/components/MobileMenu/index.tsx
  src/components/NavigationBarV2/components/NavigationLinks/index.tsx
  src/components/NavigationBarV2/components/SocialMediaIcons/SocialMediaIcons.module.scss
  src/components/NavigationBarV2/components/SocialMediaIcons/index.tsx
  src/components/NavigationBarV2/index.tsx
  src/components/NavigationBarV2/types.ts
  src/index.ts
Labels: PR: Ready-For-Review, Priority: 4 - Low

#334 [feat]: Create quests banner for store UI lib
  package.json
  src/assets/banners/CreditsCredits.png
  src/assets/banners/TreasureChst.png
  src/assets/images/Line.svg
  src/assets/images/index.tsx
  src/components/Icons/index.tsx
  src/components/QuestsBanner/QuestsBanner.module.scss
  src/components/QuestsBanner/QuestsBanner.stories.tsx
  src/components/QuestsBanner/index.tsx
  src/index.ts
Labels: PR: Ready-For-Review

#352 [Quests] Add points balance component
  src/assets/FallbackPoints.svg
  src/assets/G7Credits.png
  src/components/PointsBalance/PointsBalance.stories.tsx
  src/components/PointsBalance/index.module.scss
  src/components/PointsBalance/index.tsx
  src/index.ts
Labels: PR: Ready-For-Review

#356 [feat]: Add rewardImage prop
  package.json
  src/components/QuestCard/QuestCard.stories.tsx
  src/components/QuestCard/index.module.scss
  src/components/QuestCard/index.tsx
Labels: Priority: 1 - Highest, PR: Ready-For-Review
