Repository HyperPlay-Gaming/hyperplay-ui, pull requests merged in 2024-08, with the labels that each got.

#361 [feat]: Modify `QuestDetails` with latest design
  package.json
  src/components/QuestDetails/QuestDetails.stories.tsx
  src/components/QuestDetails/QuestDetailsStory.module.scss
  src/components/QuestDetails/index.module.scss
  src/components/QuestDetails/index.tsx
  src/components/QuestDetails/types.ts
  yarn.lock
Labels: Priority: 1 - Highest, PR: Ready-For-Review

#365 [Feat] add search bar to summary table
  package.json
  src/components/QuestsSummaryTable/QuestsSummaryTable.stories.tsx
  src/components/QuestsSummaryTable/index.module.scss
  src/components/QuestsSummaryTable/index.tsx
  src/components/SearchBar/SearchBar.module.scss
  src/components/SearchBar/index.tsx
Labels: PR: Ready-For-Review

#374 [feat]: Updated the carousel with latest proposed design
  package.json
  src/assets/G7Credits.png
  src/assets/banners/CreditsCredits.png
  src/assets/banners/TreasureChest.png
  src/assets/banners/TreasureChst.png
  src/components/QuestsBanner/QuestsBanner.module.scss
  src/components/QuestsBanner/QuestsBanner.stories.tsx
  src/components/QuestsBanner/index.tsx
Labels: Priority: 1 - Highest, PR: Ready-For-Review

#370 [feat]: Allow QuestCard to accept div attributes
  package.json
  src/components/QuestCard/QuestCard.stories.tsx
  src/components/QuestCard/index.tsx
Labels: PR: Ready-For-Review, Priority: 2 - High

#378 [feat]: Added View Reward and Claimed
  package.json
  src/assets/images/LinkExternal.svg
  src/assets/images/index.tsx
  src/components/Icons/index.tsx
  src/components/QuestDetails/QuestDetails.stories.tsx
  src/components/QuestDetails/components/Reward/index.module.scss
  src/components/QuestDetails/components/Reward/index.tsx
  src/components/QuestDetails/components/Rewards/RewardsRow/index.tsx
  src/components/QuestDetails/components/Rewards/index.tsx
  src/components/QuestDetails/index.tsx
  src/components/QuestDetails/types.ts
Labels: PR: Ready-For-Review, Priority: 2 - High

#379 [fix]: Update aspect ratio of quest banner
  package.json
  src/components/QuestsBanner/QuestsBanner.module.scss
Labels: Priority: 2 - High

#369 [feat]: Added markdown to quest details
  package.json
  src/components/MarkdownDescription/MarkdownDescription.module.scss
  src/components/MarkdownDescription/MarkdownDescription.stories.tsx
  src/components/MarkdownDescription/index.tsx
  src/components/QuestDetails/QuestDetails.stories.tsx
  src/components/QuestDetails/QuestDetailsStory.module.scss
  src/components/QuestDetails/index.module.scss
  src/components/QuestDetails/types.ts
  src/index.ts
  yarn.lock
Labels: PR: Ready-For-Review, Priority: 2 - High

#381 [fix]: Fixed view reward will only show if there is marketplace link available
  package.json
  src/components/QuestDetails/QuestDetails.stories.tsx
  src/components/QuestDetails/components/Reward/index.tsx
Labels: Priority: 2 - High

#382 [feat]: Add id, on scroll event for quests list
  package.json
  src/components/QuestsSummaryTable/index.tsx
Labels: PR: Ready-For-Review, Priority: 2 - High

#376 feat(check-email): add support for manual code input
  package.json
  src/components/CheckEmail/CheckEmail.module.scss
  src/components/CheckEmail/CheckEmail.stories.tsx
  src/components/CheckEmail/index.tsx
  src/components/TextInput/TextInput.stories.tsx
  src/styles/utilities/_inputs.scss
Labels: PR: Ready-For-Review

#385 feat(navbar): add support for user avatar and reorder layout
  package.json
  src/components/NavBar/NavBar.module.scss
  src/components/NavBar/NavBar.stories.tsx
  src/components/NavBar/index.tsx
Labels: PR: Ready-For-Review
