Repository HyperPlay-Gaming/hyperplay-ui, pull requests merged in 2025-01, with the labels that each got.

#421 [tech] Bump mantine version to latest
  .eslintrc.cjs
  .github/workflows/lint.yml
  .github/workflows/publish-ui.yml
  .github/workflows/storybook-tests.yml
  package.json
  src/components/RewardFormCard/RewardFormCard.stories.tsx
  yarn.lock
Labels: PR: Ready-For-Review, Type: Tech

#426 [Fix] Storybook tests
  .github/workflows/storybook-tests.yml
Labels: PR: Ready-For-Review

#428 [UI] Add new badge colors
  src/components/Sticker/index.module.scss
  src/components/Sticker/index.tsx
Labels: PR: Ready-For-Test

#424 [UI]Added onHover popup to the Stores logo on Library Page
  package.json
  src/components/GameCard/GameCard.module.scss
  src/components/GameCard/GameCard.stories.tsx
  src/components/GameCard/components/StoreLogo/index.tsx
  src/components/GameCard/index.tsx
Labels: PR: Ready-For-Test

#429 [Feature] Add game name to quest details component
  package.json
  src/components/QuestDetails/QuestDetails.stories.tsx
  src/components/QuestDetails/index.module.scss
  src/components/QuestDetails/index.tsx
  src/components/QuestDetails/types.ts
Labels: PR: Ready-For-Review
